version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    entrypoint: ["python3"]
    command:
      [ 
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5678",
        "-m",
        "uvicorn",
        "main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000

volumes:
  node_modules_cache: