FROM node:18-slim

WORKDIR /app

# Copy package files and install dependencies
COPY ./frontend/package*.json ./
RUN npm install

# Copy source files
COPY ./frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
